name: ChunkGenerator
main: muqsit\chunkgenerator\Loader
api: 4.0.0-BETA7
version: 0.0.2
commands:
  cgen:
    usage: /cgen <world> <minchunkx> <minchunkz> <maxchunkx> <maxchunkz>
    permission: chunkgenerator.command
permissions:
  chunkgenerator.command:
    default: op